name: Bright

on:
  pull_request:
    branches:
      - '*'

permissions:
  checks: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRIGHT_TARGET_URL: http://127.0.0.1:3000
      BRIGHT_HOSTNAME: ${{ vars.BRIGHT_HOSTNAME }}
      BRIGHT_PROJECT_ID: ${{ vars.BRIGHT_PROJECT_ID }}
      BRIGHT_AUTH_ID: ${{ vars.BRIGHT_AUTH_ID }}
      BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Use Node.js 20 for application setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install application dependencies
        run: |
          npm install

      - name: Start application
        run: |
          npm start &
          until nc -zv 127.0.0.1 3000; do sleep 1; done

      - name: Use Node.js 22 for security tests
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install SecTesterJS dependencies
        run: |
          npm i --save=false --prefix .brightsec @sectester/core @sectester/repeater @sectester/scan @sectester/runner @sectester/reporter

      - name: Run security tests
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts