name: Bright

on:
  pull_request:
    branches:
      - "*"

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BRIGHT_HOSTNAME: development.playground.brightsec.com
      BRIGHT_PROJECT_ID: kzDSPViNAfFv4AmWL4w3a1
      BRIGHT_TARGET_URL: http://127.0.0.1:3000
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install application dependencies
        run: |
          npm install
          cd frontend
          npm install

      - name: Start application
        run: npm start &

      - name: Wait for application to be ready
        run: |
          sudo apt-get install -y netcat
          until nc -zv 127.0.0.1 3000; do
            echo "Waiting for application to be ready..."
            sleep 5
          done

      - name: Authenticate with Bright
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: ${{ env.BRIGHT_HOSTNAME }}
          BRIGHT_PROJECT_ID: ${{ env.BRIGHT_PROJECT_ID }}
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Install SecTesterJS dependencies
        run: npm i --save=false --prefix .brightsec @sectester/core @sectester/repeater @sectester/scan @sectester/runner @sectester/reporter

      - name: Run security tests
        env:
          BRIGHT_AUTH_ID: ${{ vars.BRIGHT_AUTH_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRIGHT_TOKEN: ${{ env.BRIGHT_TOKEN }}
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test-concurrency=4 --test .brightsec/tests/*.test.ts
